---
# tasks file for apigee-opdk-setup-os-ds
- name: Update ipv4 tcp timeout for cassandra
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: '{{ apigee_net_ipv4_tcp_fin_timeout }}'
    state: present
  tags:
  - os_tuning

- name: Update vm max map count for cassandra
  sysctl:
    name: vm.max_map_count
    value: '{{ apigee_max_map_count }}'
    state: present
  tags:
  - os_tuning

- name: Update limits.conf
  copy:
    src: apigee.limits.conf
    dest: /etc/security/limits.d/apigee.limits.conf
    owner: root
    group: root
    mode: 0644
  tags:
  - os_tuning
