---
# tasks file for opdk-setup-os-ds
- name: Update ipv4 tcp timeout for cassandra
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^(net.ipv4.tcp_fin_timeout)"
    line: '\1 = {{ apigee_net_ipv4_tcp_fin_timeout }}'
    backup: yes
    backrefs: yes

- name: Update vm max map count for cassandra
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^(vm.max_map_count)"
    line: '\1 = {{ apigee_max_map_count }}'
    backup: yes
    backrefs: yes

- name: Update limits.conf
  copy:
    src: apigee-ds.limits.conf
    dest: /etc/security/limits.d/apigee-ds.limits.conf
    owner: root
    group: root
    mode: 0644
